#!/bin/bash

case $BLOCK_BUTTON in
	1) xbacklight -inc 5 ;;
	2) ~/.scripts/brightness ;;
	3) xbacklight -dec 5 ;;
esac

printf "<span foreground=\"#a0a0ff\"> % s%% </span>" "$(xbacklight | sed -e 's/\([0-9]\+\)\..*/\1/g')"
