#!/bin/bash

. ~/.cache/wal/colors.sh

case $BLOCK_BUTTON in
	1) notify-send "HIGH CPU PROCESSES:" \
		"$(ps axch -o cmd:15,%cpu --sort=-%cpu | head | xargs printf '%s %s%%\n')" ;;

	3) st htop ;;
esac

temp="$(sensors "pch_skylake-*" | awk -F'[\:\+°\.]' '/temp1/ {print $3}' 2>/dev/null)"

color="$color4"
if [ $temp -gt "55" ]; then
	color="#ff0000"
fi

printf " %s°C\n\n" "$temp"
printf "$color"
