#!/bin/bash

case $BLOCK_BUTTON in
	1) notify-send "HIGH MEM PROCESSES:" \
		"$(ps axch -o cmd:15,%mem --sort=-%mem | head | xargs printf '%s %s%%\n')" ;;
esac


mem=$(free -m --si | awk '/^Mem:/ {print $3 " MB"}')
printf '<span foreground="#30af30">  %s </span>' "$mem"

