#!/bin/bash
ICON=$HOME/.scripts/pictures/lock.png
TMPBG=/tmp/screen.png
scrot $TMPBG
convert $TMPBG -scale 4% -scale 2500% $TMPBG
convert $TMPBG $ICON -gravity center -composite -matte $TMPBG
i3lock -u -c 000000 -i $TMPBG
