#!/bin/bash

# The whole idea of this script was stole from Luke Smith

sel="$(xclip -o)"
[ -z "$sel" ] && exit 1

Search() {
	qutebrowser "https://duckduckgo.com/?q=$@" ;
}

Maps() {
	qutebrowser "https://openstreetmap.org/search?query=$@" ;
}

QRCode() {
	qrencode "$@" -s 10 -o /tmp/qr.png && sxiv /tmp/qr.png ;	
}

cmd="$(declare -F | awk '{print $3}' | dmenu -fn Monospace:11 -h 32 -p "$sel selected: " -l 5)"

[ -z "$cmd" ] || "$cmd" "$sel"
